force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Description of the sold project</description>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TeamProgress__c.field-meta.xml
<CustomField>
    <fullName>TeamProgress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamProgress</label>
    <referenceTo>TeamProgress__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/TeamProgress__c.object-meta.xml
<CustomObject>
    <label>TeamProgress</label>
    <nameField>
        <label>TeamProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamProgress__c/fields/EndDateAllocated__c.field-meta.xml
<CustomField>
    <fullName>EndDateAllocated__c</fullName>
    <label>EndDateAllocated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>TeamProgresses</relationshipLabel>
    <relationshipName>TeamProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/StartDateAllocated__c.field-meta.xml
<CustomField>
    <fullName>StartDateAllocated__c</fullName>
    <label>StartDateAllocated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AllocationRequestHelper.cls
public with sharing class AllocationRequestHelper {

    public static List <TeamProgress__c> teamProgressBadList = new List <TeamProgress__c>();

    public static List <TeamProgress__c> validateTeamProgress (List <TeamProgress__c> TeamProRequestedList ){

        // recorrer el alocationList y llenar el set de ids
        Set <String> resourcesIdsSet = new Set <String>();
        for(TeamProgress__c teamP : TeamProRequestedList){
        resourcesIdsSet.add(teamP.Resource__c);
        }

        //Se traen todos los TeamProgress de los usuarios
        List<TeamProgress__c> teamProgressList = [SELECT  Resource__c, StartDateAllocated__c, EndDateAllocated__c, Project__c FROM  TeamProgress__c WHERE Resource__c IN  :resourcesIdsSet];

        //recorrer Lista de TeamProRequestedList (todos los usuarios y fechas que se solicita alocar)
        for(TeamProgress__c teamPR :TeamProRequestedList){
            //recorrer el TeamProgress (Todos los teamProgress existentes en relacion a los ids de usuario)
            for(TeamProgress__c teamP : teamProgressList){
                //validar si existe algun TeamProgress que se cruce con la fecha solicitada
                if(teamP.Resource__c == teamPR.Resource__c ){
                    validateHelper(teamP, teamPR);
                }
            }
        }
        return teamProgressBadList;
    }

    private static void validateHelper(TeamProgress__c teamP, TeamProgress__c teamPR){
          if (teamPR.StartDateAllocated__c <= teamP.StartDateAllocated__c && teamPR.EndDateAllocated__c >= teamP.StartDateAllocated__c) {
            teamProgressBadList.add(teamPR);
          } else if(teamPR.StartDateAllocated__c >= teamP.StartDateAllocated__c && teamPR.EndDateAllocated__c >= teamP.StartDateAllocated__c && teamPR.StartDateAllocated__c <= teamP.EndDateAllocated__c) {
            teamProgressBadList.add(teamPR);
          }
    }
}