force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Description of the sold project</description>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/QuantityHours__c.field-meta.xml
<CustomField>
    <fullName>QuantityHours__c</fullName>
    <label>QuantityHours</label>
    <summarizedField>ProjectLineItem__c.QuantityHours__c</summarizedField>
    <summaryForeignKey>ProjectLineItem__c.ProjectAssigned__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TeamProgress__c.field-meta.xml
<CustomField>
    <fullName>TeamProgress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamProgress</label>
    <referenceTo>TeamProgress__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>ProyectLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/HoursPendingToAssign__c.field-meta.xml
<CustomField>
    <fullName>HoursPendingToAssign__c</fullName>
    <formula>QuantityHours__c -  QuantityHoursAllocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HoursPendingToAssign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/ProjectAssigned__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssigned__c</fullName>
    <label>ProjectAssigned</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjectLineItems</relationshipLabel>
    <relationshipName>ProjectLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/QuantityHours__c.field-meta.xml
<CustomField>
    <fullName>QuantityHours__c</fullName>
    <label>QuantityHours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/QuantityHoursAllocated__c.field-meta.xml
<CustomField>
    <fullName>QuantityHoursAllocated__c</fullName>
    <label>QuantityHoursAllocated</label>
    <summarizedField>TeamProgress__c.QuantityHoursAllocated__c</summarizedField>
    <summaryForeignKey>TeamProgress__c.ProjectLineItem__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeamProgress__c/TeamProgress__c.object-meta.xml
<CustomObject>
    <label>TeamProgress</label>
    <nameField>
        <label>TeamProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamProgress__c/fields/EndDateAllocated__c.field-meta.xml
<CustomField>
    <fullName>EndDateAllocated__c</fullName>
    <label>EndDateAllocated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>TeamProgresses</relationshipLabel>
    <relationshipName>TeamProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>TeamProgresses</relationshipLabel>
    <relationshipName>TeamProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/QuantityHours__c.field-meta.xml
<CustomField>
    <fullName>QuantityHours__c</fullName>
    <label>QuantityHours</label>
    <summarizedField>Task__c.RecordHours__c</summarizedField>
    <summaryForeignKey>Task__c.AssignedResource__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/QuantityHoursAllocated__c.field-meta.xml
<CustomField>
    <fullName>QuantityHoursAllocated__c</fullName>
    <formula>((5 * ( FLOOR( ( EndDateAllocated__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( EndDateAllocated__c - DATE( 1900, 1, 8), 7 ) ) ) - (5 * ( FLOOR( ( StartDateAllocated__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( StartDateAllocated__c - DATE( 1900, 1, 8), 7 ) ) ))*8</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QuantityHoursAllocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/RatePerHour__c.field-meta.xml
<CustomField>
    <fullName>RatePerHour__c</fullName>
    <label>RatePerHour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/StartDateAllocated__c.field-meta.xml
<CustomField>
    <fullName>StartDateAllocated__c</fullName>
    <label>StartDateAllocated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <formula>FirstName__c &amp; &quot; &quot;  &amp; LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FullName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/RatePerHour__c.field-meta.xml
<CustomField>
    <fullName>RatePerHour__c</fullName>
    <label>RatePerHour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AllocationService.cls
public with sharing class AllocationService {

  private static final List <String> TYPE_OF_ROLES = new List<String> 
   {'Developer', 'Consultant', 'Architect', 'Project Manager'};
 
  @AuraEnabled(cacheable=true)
  public static List <ProjectLineItem__c> getRolesWhitoutAssignment (String projectId) {
    String query = 'SELECT '  
                 + 'Id, Role__c, HoursPendingToAssign__c, QuantityHours__c, QuantityHoursAllocated__c ' 
                 + 'FROM ProjectLineItem__c ' 
                 + 'WHERE ProjectAssigned__c = : projectId '
                 + 'AND HoursPendingToAssign__c > 0 '
                 + 'WITH SECURITY_ENFORCED ';
    String finalQuery = String.escapeSingleQuotes(query);             
    return Database.query(finalQuery); 
  }

  @AuraEnabled(cacheable=true)
  public static List <ProjectLineItem__c> getTeamProgressesByProject (String projectId) {
    String query = 'SELECT '  
                 + 'Resource__r.Fullname__c, ' 
                 + 'Resource__r.Role__c, '
                 + 'QuantityHoursAllocated__c '
                 + 'FROM teamProgress__c ' 
                 + 'WHERE ProjectLineItem__r.ProjectAssigned__c = : projectId '
                 + 'WITH SECURITY_ENFORCED ';
    String finalQuery = String.escapeSingleQuotes(query);             
    return Database.query(finalQuery); 
  }

  @AuraEnabled(cacheable=true)
  public static List <ProjectLineItem__c> getHoursPendingToAssignByRole (String projectId, String RoleName) {
    String query = 'SELECT '  
                 + 'HoursPendingToAssign__c ' 
                 + 'FROM ProjectLineItem__c ' 
                 + 'WHERE ProjectAssigned__c = : projectId '
                 + 'AND HoursPendingToAssign__c > 0 '
                 + 'AND Role__c = : RoleName '
                 + 'WITH SECURITY_ENFORCED ';
    String finalQuery = String.escapeSingleQuotes(query);             
    return Database.query(finalQuery); 
  }
  
  @AuraEnabled(cacheable=true)
  public static List <User> getResourcesByRole (String roleName){

    String query = 'SELECT '
                 + 'Id ,FirstName,LastName,RatePerHour__c,Role__c,FullName__c '
                 + 'FROM User '
                 + 'WHERE  Role__c = : roleName '
                 + 'AND Role__c IN : TYPE_OF_ROLES '
                 + 'WITH SECURITY_ENFORCED ';
    String finalQuery = String.escapeSingleQuotes(query);             
    return Database.query(finalQuery);    
  }

  @AuraEnabled
  public static String allocationCreate(String alocationJson, String projectID){

    List<TeamProgress__c> teamPList = (List<TeamProgress__c>) JSON.deserialize(alocationJson, List<TeamProgress__c>.class);
    System.debug('Que recibe ??   lista-> '+ teamPList + '   project id -->' + projectID);
    List<TeamProgress__c> teamPListWithName = addName(teamPList);
    List<TeamProgress__c> teamPListWithPLI = addProjectLI(teamPListWithName,projectID);
    System.debug('Esta es la lista de teamProgress completos' +  teamPListWithPLI);

    insert teamPListWithPLI;

    return 'Se creo la alocacion con exito';
  }
  
  private static List <TeamProgress__c> addProjectLI(List <TeamProgress__c> teamProgressList, String projectID){
    //1. Tenemos una lista de teamP sin su respectivo PLI  OK----
    List <TeamProgress__c> newTeamProgressList = new List <TeamProgress__c>();
    //2. Necesitamos traer el id del project  OK ---
    System.debug('Este es el id del project DESDE EL METODO ADD: '+ projectID);
    //3. Necesitamos traer la lista de los PLI asociados a ese proyecto
    Map <String,ProjectLineItem__c> roleNamePLIAndPLIObject= new Map<String, ProjectLineItem__c>();
    //llenar el mapa
    List<ProjectLineItem__c> pliList = [SELECT Id, Role__c FROM ProjectLineItem__c WHERE ProjectAssigned__c =: projectID];
    for(ProjectLineItem__c pli : pliList){
      roleNamePLIAndPLIObject.put(pli.Role__c, pli);
    }
    //4. Necesitamos traer el role por resource del TeamProgress
    Set <String> resourcesIdsSet = new Set <String>();
    for(TeamProgress__c teamP : teamProgressList){
    resourcesIdsSet.add(teamP.Resource__c);
    }
    //traer datos de los usuarios
    Map <Id, User> dataUserMap = new Map <Id, User>([SELECT FirstName, LastName, Role__c FROM User WHERE Id IN :resourcesIdsSet]);
    //. Necesitamos agregar el PLI a cada TeamP
    for(TeamProgress__c teamP : teamProgressList){
      //nos traermos el nombre del rol del current teapP
      String userRoleName = dataUserMap.get(teamP.Resource__c).Role__c;
      String pliID = roleNamePLIAndPLIObject.get(userRoleName).Id;
      teamP.ProjectLineItem__c = pliID;
      //String teamName = dataUserMap.get(teamP.Resource__c).FirstName + ' - ' + dataUserMap.get(teamP.Resource__c).Role__c;
      //teamP.Name = teamName;
      newTeamProgressList.add(teamP);
    }
    return newTeamProgressList;
  }

  private static List <TeamProgress__c> addName(List <TeamProgress__c> teamProgressList){
    List <TeamProgress__c> newTeamProgressList = new List <TeamProgress__c>();
    //recorrer la lista para traer los Resource__c
    Set <String> resourcesIdsSet = new Set <String>();
    for(TeamProgress__c teamP : teamProgressList){
    resourcesIdsSet.add(teamP.Resource__c);
    }
    //traer datos de los usuarios
    Map <Id, User> dataUserMap = new Map <Id, User>([SELECT FirstName, LastName, Role__c FROM User WHERE Id IN :resourcesIdsSet]);
    //agrega los nombres a los teamProgress
    for(TeamProgress__c teamP : teamProgressList){
      String teamName = dataUserMap.get(teamP.Resource__c).FirstName + ' - ' + dataUserMap.get(teamP.Resource__c).Role__c;
      teamP.Name = teamName;
      newTeamProgressList.add(teamP);
    }
    return newTeamProgressList;
  }
}
/********************    PRUEBAS EN VENTANA ANONIMA           ********************** 
  METODO getRolesWhitoutAssignment
  Id projectId = [SELECT Id FROM Project__c LIMIT 1][0].Id;
  system.debug(AllocationService.getRolesWhitoutAssignment(projectId));

  METODO getResourcesByRole
  system.debug(AllocationService.getResourcesByRole('Developer'));

  METODO  allocationCreate
AllocationService.allocationCreate('[{"Resource__c" : "0058a00000LWPN6AAP", "Project__c" : "a028a00001KQaM1AAL","startDateAllocated__c" : "2022-05-17","endDateAllocated__c" : "2022-05-18"}]');

*/