force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Description of the sold project</description>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TeamProgress__c.field-meta.xml
<CustomField>
    <fullName>TeamProgress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamProgress</label>
    <referenceTo>TeamProgress__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>ProyectLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/HoursPendingToAssign__c.field-meta.xml
<CustomField>
    <fullName>HoursPendingToAssign__c</fullName>
    <formula>QuantityHours__c -  QuantityHoursAllocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HoursPendingToAssign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/ProjectAssigned__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssigned__c</fullName>
    <label>ProjectAssigned</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjectLineItems</relationshipLabel>
    <relationshipName>ProjectLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeamProgress__c/TeamProgress__c.object-meta.xml
<CustomObject>
    <label>TeamProgress</label>
    <nameField>
        <label>TeamProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamProgress__c/fields/EndDateAllocated__c.field-meta.xml
<CustomField>
    <fullName>EndDateAllocated__c</fullName>
    <label>EndDateAllocated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>TeamProgresses</relationshipLabel>
    <relationshipName>TeamProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>TeamProgresses</relationshipLabel>
    <relationshipName>TeamProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/RatePerHour__c.field-meta.xml
<CustomField>
    <fullName>RatePerHour__c</fullName>
    <label>RatePerHour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/StartDateAllocated__c.field-meta.xml
<CustomField>
    <fullName>StartDateAllocated__c</fullName>
    <label>StartDateAllocated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/RatePerHour__c.field-meta.xml
<CustomField>
    <fullName>RatePerHour__c</fullName>
    <label>RatePerHour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/alocationService.cls
public class alocationService {

   private static final List <String> typeOfRoles = new List<String> 
   {'Developer', 'Consultant', 'Architect', 'Project Manager'};



  public static List <ProjectLineItem__c> getRolesWhitoutAssignment (String projectId) {

    return [SELECT Id,
     Role__c,
     HoursPendingToAssign__c 
     FROM ProjectLineItem__c 
     WHERE ProjectAssigned__c = : projectId 
     AND HoursPendingToAssign__c > 0 ];

  }
  
  public static List <User> getResourcesByRol (String roleName){

    return [
    SELECT Id,
    FirstName,
    LastName,
    RatePerHour__c,
    Role__c FROM User
    WHERE  Role__c = : roleName
    AND Role__c IN : typeOfRoles
    AND isActive = True
    ];
  
  }

public static Boolean validateAvailabilityByUser (String userId, Date startDateR, Date endDateR) {

  Boolean response = true;

  List<TeamProgress__c> TeamProgressList = [
    SELECT StartDateAllocated__c, EndDateAllocated__c, Project__c
    FROM TeamProgress__c  
    WHERE Resource__c = : userId
  ];
  
  for (TeamProgress__c teamP : TeamProgressList) {
    
      if (startDateR < teamP.StartDateAllocated__c && endDateR > teamP.StartDateAllocated__c) {
      return response = false;
    } else if(startDateR > teamP.StartDateAllocated__c && endDateR > teamP.StartDateAllocated__c && startDateR < teamP.EndDateAllocated__c) {
      
    return response = false;
    }
    }


 // System.debug(TeamProgressList);

  return response;

}

}


   /*
   Id projectId = [SELECT Id FROM Project__c LIMIT 1][0].Id;
   
system.debug(alocationService.getRolesWhitoutAssignment(projectId));
   */