force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>ProyectLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/AssignedResource__c.field-meta.xml
<CustomField>
    <fullName>AssignedResource__c</fullName>
    <label>AssignedResource</label>
    <referenceTo>TeamProgress__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimatedHours__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHours__c</fullName>
    <formula>((5 * ( FLOOR( ( EndTaskDate__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( EndTaskDate__c - DATE( 1900, 1, 8), 7 ) ) ) - (5 * ( FLOOR( ( StartTaskDate__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( StartTaskDate__c - DATE( 1900, 1, 8), 7 ) ) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EstimatedHours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/RecordHours__c.field-meta.xml
<CustomField>
    <fullName>RecordHours__c</fullName>
    <label>RecordHours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/StartTaskDate__c.field-meta.xml
<CustomField>
    <fullName>StartTaskDate__c</fullName>
    <label>StartTaskDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeamProgress__c/TeamProgress__c.object-meta.xml
<CustomObject>
    <label>TeamProgress</label>
    <nameField>
        <label>TeamProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamProgresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamProgress__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>TeamProgresses</relationshipLabel>
    <relationshipName>TeamProgresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamProgress__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamProgresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LoadedServiceHours.cls
public with sharing class LoadedServiceHours {
    private static final List <String> STATUS_TASK = new List<String> 
   {'In Progress','Not Started'};
   

    @AuraEnabled(cacheable=true)
    public static List <Task__c> getPendingTaskbyResourceAndProject (String userId, String projectId) {
    return [SELECT  
            Id, Name, Status__c, EstimatedHours__c,RecordHours__c, StartTaskDate__c
            //AssignedResource__r.Resource__c,
            //AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id 
            FROM Task__c 
            WHERE Status__c in : (STATUS_TASK) 
            AND AssignedResource__r.Resource__c = : userId
            AND AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id = : projectId 
            ORDER BY Status__c DESC, StartTaskDate__c ];
    }

    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getPendingTaskbyResourceCount(String userId) {
            //Trae un array de AggregateResult
            List<AggregateResult> ls = [
            SELECT AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Name, Count(Task__c.Id),
                   AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.id 
            FROM   Task__c
            WHERE  Status__c in : STATUS_TASK
            AND    AssignedResource__r.Resource__c = : userId 
            Group by Task__c.AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Name, Task__c.AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id
            ];

            //System.debug('Respuesta: --->'+ ls);
            return ls;
    }

    @AuraEnabled(cacheable=false)
    public static String updateTaskStatus(String taskId, String newStatus) {

        Task__c taskToUpdate = [SELECT Id, Status__c 
                                FROM Task__c 
                                WHERE Id = : taskId][0];

        taskToUpdate.Status__c = newStatus;
        update taskToUpdate;
            return 'Successfully Updated';
    }

    @AuraEnabled(cacheable=true)
    public static String addTaskRecordHours(String taskId, Integer numberHours) {

        Task__c taskToUpdate = [SELECT Id, RecordHours__c 
                                FROM Task__c 
                                WHERE Id = : taskId][0];

        taskToUpdate.RecordHours__c += numberHours;
        update taskToUpdate;

            return 'Successfully Added';
    }
}


/* 


System.debug('Esta es la lista de task' + JSON.serializePretty( tl ));



SELECT Id, Name, Status__c, EstimatedHours__c,RecordHours__c, StartTaskDate__c, AssignedResource__r.Resource__c,
AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id
FROM Task__c
WHERE Status__c in ('In Progress','Not Started')
AND AssignedResource__r.Resource__c = '0058c00000BiaBWAAZ'
AND AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id = 'a028c00000ZLAUrAAP'
ORDER BY Status__c DESC, StartTaskDate__c 



SELECT Status__c, Count(Task__c.Id) numberPendingTask
FROM Task__c
WHERE Status__c in ('In Progress','Not Started')
AND AssignedResource__r.Resource__c = '0058c00000BiaBWAAZ'
Group by Task__c.Status__c


DEVELOPER CONSOLE

METODO getPendingTaskbyResourceAndProject
List<Task__c> tl = [SELECT Id, Name, Status__c, EstimatedHours__c,RecordHours__c, 
AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id
FROM Task__c ];

__________  METODO getPendingTaskbyResourceCount  __________________________________________
 List <String> STATUS_TASK = new List<String> {'In Progress','Not Started'};
       String userId = '0058c00000BiaBWAAZ';

List<AggregateResult> ls = [SELECT AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Name, Count(Task__c.Id), AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.id FROM Task__c
            WHERE Status__c in : STATUS_TASK
            AND AssignedResource__r.Resource__c = : userId 
            Group by Task__c.AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Name, Task__c.AssignedResource__r.ProjectLineItem__r.ProjectAssigned__r.Id
            ];

System.debug('Result -> '+ ls[0].get('Name') + '  , ' + ls[0].get('expr0') + ' , '   + ls[0].get('Id'));


anonima-> 
String userId = '0058c00000BiaBWAAZ';
System.debug(LoadedServiceHours.getPendingTaskbyResourceCount(userId));

________________________________________________________________________________

__________  METODO updateTaskStatus  __________________________________________
String newStatus = 'Not Started';
String taskId = 'a038c00001fRMkVAAW';
System.debug(LoadedServiceHours.updateTaskStatus(taskId, newStatus));
*/